const Disclaimer = () => {
  return (
    <div className="max-w-5xl text-justify text-gray-600">
      <h1 className="mb-4 text-2xl font-medium text-black/40">Disclaimer</h1>
      <div className="space-y-5 leading-relaxed">
        <div>
          <h2 className="text-xl font-semibold text-gray-700">
            RightRoute™ Legal Disclaimer
          </h2>
          <p className="mt-2 italic">Last updated: 5/23/2026</p>
        </div>

        <p>
          This disclaimer applies to all visitors to this website and to all
          users of the Right Route platform and related services (collectively,
          the &quot;Services&quot;) provided by Leavitt &amp; Davis LLC
          (&quot;L&amp;D,&quot; &quot;we,&quot; &quot;us,&quot; or
          &quot;our&quot;). By accessing this website or using the Services, you
          acknowledge that you have read, understood, and agree to the terms of
          this disclaimer. If you do not agree, do not access this website or
          use the Services. This disclaimer supplements and is incorporated into
          the Right Route Terms of Service and Privacy Policy. In the event of
          any conflict between this disclaimer and the Terms of Service, the
          Terms of Service govern.
        </p>

        <section>
          <h3 className="font-semibold text-gray-700">
            1. Decision-Support Tool — Not a Compliance Guarantee
          </h3>
          <p className="mt-3">
            Right Route is a software platform designed to assist carriers,
            trucking companies, brokers, and dispatchers in planning routes for
            oversized and overweight load moves. The route plans, clearance
            analyses, permit checklists, height and weight recommendations,
            bridge assessments, and all other outputs generated by the Services
            (collectively, &quot;Route Outputs&quot;) are decision-support tools
            only.
          </p>
          <p className="mt-3">Route Outputs do not constitute:</p>
          <ul className="mt-3 list-disc space-y-3 pl-6">
            <li>
              A guarantee that any proposed route is safe, physically passable,
              or legally compliant;
            </li>
            <li>
              A legal opinion or engineering assessment regarding route
              suitability;
            </li>
            <li>
              A substitute for obtaining required oversize/overweight permits
              from applicable state and local authorities;
            </li>
            <li>
              A substitute for compliance with applicable federal regulations,
              including vehicle weight limitations under 23 U.S.C. § 127 and
              Federal Highway Administration routing requirements under 23 C.F.R.
              Part 658; or
            </li>
            <li>
              A substitute for compliance with applicable state
              oversize/overweight statutes, permitting requirements, and escort
              or pilot vehicle requirements.
            </li>
          </ul>
          <p className="mt-3">
            You remain solely responsible for independently verifying all Route
            Outputs, obtaining all required permits, and making all final routing
            and operational decisions before commencing any move.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">
            2. Third-Party Data — Accuracy Not Guaranteed
          </h3>
          <p className="mt-3">
            The Services incorporate data sourced from third parties, including
            state departments of transportation, the Federal Highway
            Administration, bridge inspection and rating databases, GIS mapping
            providers, weather services, and other external sources
            (&quot;Third-Party Data&quot;). L&amp;D does not independently verify,
            warrant, or guarantee the accuracy, completeness, timeliness, or
            fitness for any particular purpose of Third-Party Data.
          </p>
        </section>
      </div>
    </div>
  )
}

export default Disclaimer
