const Disclaimer = () => {
  return (
    <div className="max-w-5xl text-justify text-gray-600">
      <h1 className="mb-8 text-xl font-normal text-[#999] md:text-2xl">Disclaimer</h1>
      <div className="space-y-5 leading-relaxed text-sm">
        <div>
          <h2 className="text-xl font-semibold text-gray-700">RightRoute™ Legal Disclaimer</h2>
          <p className="mt-2 italic">Last updated: 5/23/2026</p>
        </div>

        <p>
          This disclaimer applies to all visitors to this website and to all users of the RightRoute
          platform and related services (collectively, the "Services") provided by Leavitt &amp; Davis
          LLC ("L&amp;D," "we," "us," or "our"). By accessing this website or using the Services, you
          acknowledge that you have read, understood, and agree to the terms of this disclaimer. If
          you do not agree, do not access this website or use the Services. This disclaimer
          supplements and is incorporated into the RightRoute Terms of Service and Privacy Policy.
          In the event of any conflict between this disclaimer and the Terms of Service, the Terms
          of Service govern.
        </p>

        <section>
          <h3 className="font-semibold text-gray-700">
            1. Decision-Support Tool — Not a Compliance Guarantee
          </h3>
          <p className="mt-3">
            RightRoute is a software platform designed to assist carriers, trucking companies,
            brokers, and dispatchers in planning routes for oversized and overweight load moves. The
            route plans, clearance analyses, permit checklists, height and weight recommendations,
            bridge assessments, and all other outputs generated by the Services (collectively, "Route
            Outputs") are decision-support tools only.
          </p>
          <p className="mt-3">Route Outputs do not constitute:</p>
          <ul className="mt-3 list-disc space-y-3 pl-6">
            <li>
              A guarantee that any proposed route is safe, physically passable, or legally
              compliant;
            </li>
            <li>
              A legal opinion or engineering assessment regarding route suitability;
            </li>
            <li>
              A substitute for obtaining required oversize/overweight permits from applicable state
              and local authorities;
            </li>
            <li>
              A substitute for compliance with applicable federal regulations, including vehicle
              weight limitations under 23 U.S.C. § 127 and Federal Highway Administration routing
              requirements under 23 C.F.R. Part 658; or
            </li>
            <li>
              A substitute for compliance with applicable state oversize/overweight statutes,
              permitting requirements, and escort or pilot vehicle requirements.
            </li>
          </ul>
          <p className="mt-3">
            You remain solely responsible for independently verifying all Route Outputs, obtaining
            all required permits, and making all final routing and operational decisions before
            commencing any move.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">
            2. Third-Party Data — Accuracy Not Guaranteed
          </h3>
          <p className="mt-3">
            The Services incorporate data sourced from third parties, including state departments of
            transportation, the Federal Highway Administration, bridge inspection and rating
            databases, GIS mapping providers, weather services, and other external sources
            ("Third-Party Data"). L&amp;D does not independently verify, warrant, or guarantee the
            accuracy, completeness, timeliness, or fitness for any particular purpose of Third-Party
            Data.
          </p>
          <p className="mt-3">
            Third-Party Data may be outdated, incomplete, or may not reflect current road conditions,
            bridge ratings, construction, detours, or permit requirements. Bridge ratings and
            clearance data in particular are subject to change without notice due to repairs,
            inspections, and seasonal load restrictions.
          </p>
          <p className="mt-3">
            You must independently verify all Third-Party Data against current permit conditions,
            applicable regulations, and actual road and bridge conditions before commencing any move.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">
            3. AI-Processed Data — Not a Verified Document Reading
          </h3>
          <p className="mt-3">
            The Services may use artificial intelligence or machine learning tools to extract,
            summarize, classify, score, or otherwise analyze permit documents and other content you
            submit, producing AI-Processed Data, including associated confidence scores. AI-Processed
            Data is a decision-support output only.
          </p>
          <p className="mt-3 font-bold uppercase">
            AI-PROCESSED DATA MAY CONTAIN ERRORS, OMISSIONS, OR MISCLASSIFICATIONS. IT IS NOT A
            VERIFIED OR AUTHORITATIVE READING OF ANY PERMIT, REGULATION, OR OTHER DOCUMENT. YOU
            REMAIN SOLELY RESPONSIBLE FOR INDEPENDENTLY REVIEWING THE UNDERLYING DOCUMENT AND
            CONFIRMING ITS ACTUAL TERMS BEFORE RELYING ON ANY AI-PROCESSED DATA.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">4. Your Sole Responsibility</h3>
          <p className="mt-3">You are solely and exclusively responsible for:</p>
          <ul className="mt-3 list-disc space-y-3 pl-6">
            <li>
              Independently verifying all Route Outputs against current permit conditions, applicable
              federal and state regulations, and actual road and bridge conditions before commencing
              any move;
            </li>
            <li>
              Obtaining all required oversize/overweight permits from all applicable jurisdictions
              before commencing any move;
            </li>
            <li>
              Ensuring that your vehicles, loads, and operations comply with all applicable federal
              regulations (including 23 U.S.C. § 127 and 23 C.F.R. Part 658), state and local
              statutes, and permit conditions;
            </li>
            <li>
              Complying with all escort and pilot vehicle requirements under applicable law;
            </li>
            <li>
              The safety of all personnel involved in your operations; and
            </li>
            <li>
              All final routing, load, and operational decisions.
            </li>
          </ul>
          <p className="mt-3">
            The operator, not L&amp;D, is solely responsible for the safety and legality of every
            move. You agree not to use the Services as the sole basis for any move, permit
            application, load clearance decision, or mandatory regulatory filing.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">5. Limitation of Liability</h3>
          <p className="mt-3 font-bold uppercase">
            TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, L&amp;D AND ITS AFFILIATES, DIRECTORS,
            OFFICERS, EMPLOYEES, AGENTS, AND LICENSORS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT,
            INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES ARISING OUT OF OR
            RELATING TO YOUR ACCESS TO OR USE OF THE SERVICES, INCLUDING ANY ACCIDENT, INJURY,
            DEATH, PROPERTY DAMAGE, OR REGULATORY PENALTY ARISING IN CONNECTION WITH ANY OVERSIZED
            OR OVERWEIGHT LOAD MOVE WHERE THE SERVICES WERE USED, REGARDLESS OF WHETHER SUCH
            DAMAGES ARISE UNDER CONTRACT, TORT, STATUTE, OR ANY OTHER THEORY OF LIABILITY, AND EVEN
            IF L&amp;D HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
          </p>
          <p className="mt-3 font-bold uppercase">
            L&amp;D'S TOTAL CUMULATIVE LIABILITY TO YOU SHALL NOT EXCEED THE GREATER OF (A) THE TOTAL
            FEES PAID OR PAYABLE BY YOU TO L&amp;D DURING THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING
            THE EVENT GIVING RISE TO THE CLAIM, OR (B) ONE THOUSAND DOLLARS ($1,000.00).
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">6. "As Is" Basis</h3>
          <p className="mt-3 font-bold uppercase">
            THE SERVICES AND ALL ROUTE OUTPUTS ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS
            WITHOUT ANY WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING ANY WARRANTY OF
            MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, NON-INFRINGEMENT, OR THAT
            THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. L&amp;D DOES NOT WARRANT THAT ROUTE
            OUTPUTS ACCURATELY REFLECT CURRENT ROAD CONDITIONS, BRIDGE RATINGS, PERMIT REQUIREMENTS,
            OR APPLICABLE LEGAL RESTRICTIONS IN ANY JURISDICTION. L&amp;D FURTHER DOES NOT WARRANT THAT
            AI-PROCESSED DATA ACCURATELY OR COMPLETELY REFLECTS THE CONTENTS OF ANY UNDERLYING
            PERMIT DOCUMENT OR OTHER USER-SUBMITTED CONTENT.
          </p>
          <p className="mt-3">
            Some jurisdictions do not allow the exclusion of certain implied warranties. If those
            laws apply to you, some of the exclusions above may not apply.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">7. Indemnification</h3>
          <p className="mt-3">
            You agree to indemnify, defend, and hold harmless L&amp;D and its affiliates, directors,
            officers, employees, agents, and licensors from and against any and all claims, actions,
            losses, damages, liabilities, costs, and expenses (including reasonable attorneys' fees)
            arising out of or relating to: (a) your access to or use of the Services; (b) your
            violation of applicable law or any permit condition; (c) any accident, injury, death, or
            property damage arising in connection with any oversized or overweight load move where
            the Services were used; or (d) your reliance on any Route Output or AI-Processed Data
            without independent verification.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">8. Contact</h3>
          <p className="mt-3">
            Questions regarding this disclaimer may be directed to:
          </p>
          <p className="mt-3">
            LEAVITT &amp; DAVIS LLC
            <br />
            1753 US Highway 40, Suite 2, PMB 15
            <br />
            Vernal, UT 84078
            <br />
            legal@getrightroute.app
          </p>
        </section>

        <p className="mt-6">© 2026 LEAVITT &amp; DAVIS LLC. All rights reserved.</p>
        <p>
          <a className="text-[#c3c3c3]" href="mailto:legal@getrightroute.app">
            legal@getrightroute.app
          </a>
        </p>
      </div>
    </div>
  );
};

export default Disclaimer;
