const Disclaimer = () => {
  return (
    <div className="max-w-5xl text-justify text-gray-600">
      <h1 className="mb-8 text-xl font-normal text-[#999] md:text-2xl">Disclaimer</h1>
      <div className="space-y-5 leading-relaxed text-sm">
        <div>
          <h2 className="text-xl font-semibold text-gray-700">Right Route™ Legal Disclaimer</h2>
          <p className="mt-2 italic">Last updated: 5/23/2026</p>
        </div>

        <p>
          This disclaimer applies to all visitors to this website and to all users of the Right
          Route platform and related services (collectively, the &ldquo;Services&rdquo;) provided by
          Leavitt &amp; Davis LLC (&ldquo;L&amp;D,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
          &ldquo;our&rdquo;). By accessing this website or using the Services, you acknowledge that
          you have read, understood, and agree to the terms of this disclaimer. If you do not
          agree, do not access this website or use the Services. This disclaimer supplements and is
          incorporated into the Right Route Terms of Service and Privacy Policy. In the event of
          any conflict between this disclaimer and the Terms of Service, the Terms of Service
          govern.
        </p>

        <section>
          <h3 className="font-semibold text-gray-700">
            1. Decision-Support Tool — Not a Compliance Guarantee
          </h3>
          <p className="mt-3">
            Right Route is a software platform designed to assist carriers, trucking companies,
            brokers, and dispatchers in planning routes for oversized and overweight load moves. The
            route plans, clearance analyses, permit checklists, height and weight recommendations,
            bridge assessments, and all other outputs generated by the Services (collectively,
            &ldquo;Route Outputs&rdquo;) are decision-support tools only.
          </p>
          <p className="mt-3">Route Outputs do not constitute:</p>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>
              A guarantee that any proposed route is safe, physically passable, or legally
              compliant;
            </li>
            <li>
              A legal opinion or engineering assessment regarding route suitability;
            </li>
            <li>
              A substitute for obtaining required oversize/overweight permits from applicable state
              and local authorities;
            </li>
            <li>
              A substitute for compliance with applicable federal regulations, including vehicle
              weight limitations under 23 U.S.C. &sect; 127 and Federal Highway Administration
              routing requirements under 23 C.F.R. Part 658; or
            </li>
            <li>
              A substitute for compliance with applicable state oversize/overweight statutes,
              permitting requirements, and escort or pilot vehicle requirements.
            </li>
          </ul>
          <p className="mt-3">
            You remain solely responsible for independently verifying all Route Outputs, obtaining
            all required permits, and making all final routing and operational decisions before
            commencing any move.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">
            2. Third-Party Data — Accuracy Not Guaranteed
          </h3>
          <p className="mt-3">
            The Services incorporate data sourced from third parties, including state departments of
            transportation, the Federal Highway Administration, bridge inspection and rating
            databases, GIS mapping providers, weather services, and other external sources
            (&ldquo;Third-Party Data&rdquo;). L&amp;D does not independently verify, warrant, or
            guarantee the accuracy, completeness, timeliness, or fitness for any particular purpose
            of Third-Party Data.
          </p>
          <p className="mt-3">
            Third-Party Data is subject to change without notice. Bridge ratings, clearance
            measurements, road restriction data, permit route designations, and other operational
            data may not reflect current physical or legal conditions at the time you use the
            Services. Road construction, emergency restrictions, seasonal closures, and inspection
            updates may not be captured in the data available to the Services.
          </p>
          <p className="mt-3">
            You must independently verify all bridge clearances, weight limits, road restrictions,
            and permit conditions against current information from applicable state and local
            authorities before commencing any move.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">
            3. Carrier and Operator Responsibility
          </h3>
          <p className="mt-3">
            The carrier, trucking company, broker, dispatcher, or other person or entity using the
            Services to plan or coordinate a move (&ldquo;Operator&rdquo;) bears sole responsibility
            for:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>
              Verifying that the proposed route complies with all applicable federal, state, and
              local laws and regulations governing the movement of oversized and overweight loads;
            </li>
            <li>
              Obtaining all required oversize/overweight permits from applicable jurisdictions
              before commencing any move;
            </li>
            <li>
              Ensuring compliance with all applicable escort and pilot vehicle requirements;
            </li>
            <li>
              Maintaining all required insurance coverages, including minimum liability coverage
              required by federal law (49 C.F.R. &sect; 387.9) and applicable state law;
            </li>
            <li>
              Verifying actual physical clearances, road conditions, and bridge conditions along the
              proposed route before and during the move; and
            </li>
            <li>
              Complying with all applicable Federal Motor Carrier Safety Regulations (49 C.F.R.
              Parts 382&ndash;399) and any other applicable law.
            </li>
          </ul>
          <p className="mt-3">
            Right Route is a planning aid. The Operator, not L&amp;D, is responsible for the safety
            and legality of every move.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">4. Limitation of Liability</h3>
          <p className="mt-3">
            L&amp;D and its affiliates, directors, officers, employees, agents, and subcontractors
            shall not be liable for any loss, damage, injury, death, property damage, regulatory fine
            or penalty, permit violation, or other harm arising out of or in connection with:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>
              Any Route Output generated by the Services, including any routing recommendation,
              clearance analysis, or permit checklist;
            </li>
            <li>
              Any inaccuracy, incompleteness, or untimeliness in Third-Party Data incorporated into
              the Services;
            </li>
            <li>
              Any failure by an Operator to independently verify Route Outputs or comply with
              applicable law;
            </li>
            <li>
              Any accident, incident, bridge strike, overhead contact, load shift, or other event
              occurring in connection with a move planned or coordinated using the Services; or
            </li>
            <li>Any interruption, unavailability, or error in the Services.</li>
          </ul>
          <p className="mt-3 uppercase font-medium">
            TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, L&amp;D&rsquo;S TOTAL LIABILITY
            ARISING OUT OF OR IN CONNECTION WITH THIS DISCLAIMER OR THE SERVICES SHALL NOT EXCEED
            THE FEES PAID BY YOU FOR THE SERVICES IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR
            ONE THOUSAND DOLLARS ($1,000.00), WHICHEVER IS GREATER. IN NO EVENT SHALL L&amp;D BE
            LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.
          </p>
          <p className="mt-3">
            Nothing in this disclaimer limits liability for fraud or willful misconduct, or as
            otherwise required by applicable law.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">5. No Warranty</h3>
          <p className="mt-3 uppercase font-medium">
            THE SERVICES AND ALL ROUTE OUTPUTS ARE PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS
            AVAILABLE&rdquo; WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. L&amp;D EXPRESSLY
            DISCLAIMS ALL WARRANTIES, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
            PARTICULAR PURPOSE, ACCURACY, AND NON-INFRINGEMENT. L&amp;D DOES NOT WARRANT THAT THE
            SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT ROUTE OUTPUTS WILL ACCURATELY REFLECT
            CURRENT ROAD CONDITIONS, BRIDGE RATINGS, PERMIT REQUIREMENTS, OR LEGAL RESTRICTIONS IN
            ANY JURISDICTION.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">6. Governing Terms</h3>
          <p className="mt-3">
            This disclaimer is governed by the laws of the State of North Dakota. Your access to and
            use of the Services is subject to the Right Route Terms of Service and Privacy Policy,
            which are incorporated herein by reference. In the event of any conflict between this
            disclaimer and the Terms of Service, the Terms of Service govern.
          </p>
          <p className="mt-3">
            Questions about this disclaimer may be directed to:
          </p>
          <p className="mt-3">
            Leavitt &amp; Davis LLC
            <br />
            7909 Lost River Road
            <br />
            Horace, ND 58047
            <br />
            <a
              className="text-[#c3c3c3] hover:underline"
              href="mailto:legal@getrightroute.app"
            >
              legal@getrightroute.app
            </a>
          </p>
        </section>

        <p className="mt-6">&copy; 2026 LEAVITT &amp; DAVIS LLC. All rights reserved.</p>
        <p>
          <a className="text-[#c3c3c3]" href="mailto:legal@getrightroute.app">
            legal@getrightroute.app
          </a>
        </p>
      </div>
    </div>
  );
};

export default Disclaimer;
