const PrivacyPolicy = () => {
  return (
    <div className="max-w-5xl text-justify text-gray-600">
      <h1 className="mb-8 text-xl font-normal text-[#999] md:text-2xl">Privacy Policy</h1>
      <div className="space-y-5 leading-relaxed text-sm">
        <div>
          <h2 className="text-xl font-semibold text-gray-700">
            Leavitt &amp; Davis LLC - RightRoute Software™ Privacy Policy
          </h2>
          <p className="mt-2 italic">Last updated: 7/11/2026</p>
        </div>

        <section>
          <h3 className="font-semibold text-gray-700">1. Introduction</h3>
          <p className="mt-3">
            This Privacy Policy applies to the RightRoute Software platform and related services
            provided by Leavitt &amp; Davis LLC ("RightRoute", "we", "us", or "our"). It explains how
            we collect, use, share, and protect information when you access or use RightRoute
            Software as a carrier, trucking company, broker, dispatcher, or other authorized user.
          </p>
          <p className="mt-3">
            By accessing or using the Services, you agree to the collection and use of information
            as described in this Privacy Policy. If you do not agree, you must discontinue use of
            the Services.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">2. Definitions</h3>
          <p className="mt-3">
            The following defined terms apply throughout this Privacy Policy:
          </p>
          <div className="mt-3 space-y-3">
            <p>
              <strong>"Route Data"</strong> means origin, destination, waypoint, road segment,
              bridge, height/clearance, and weight-limit data, as well as permit information, load
              specifications, and other operational data entered into or generated by the Services
              in connection with planning or executing an oversized load move.
            </p>
            <p>
              <strong>"Personal Data"</strong> means any information relating to an identified or
              identifiable natural person processed through the Services, including driver name,
              contact information, and device location data.
            </p>
            <p>
              <strong>"Usage Data"</strong> means information about how you interact with the
              Services, including feature usage, session duration, device and browser
              characteristics, and log data.
            </p>
            <p>
              <strong>"Third-Party Data"</strong> means data sourced from state departments of
              transportation, mapping providers, bridge databases, weather services, and other
              external data providers integrated with the Services.
            </p>
            <p>
              <strong>"Derived Data"</strong> means analytics, models, benchmarks, and other
              outputs created by RightRoute using Route Data, Personal Data, Usage Data, or
              Third-Party Data.
            </p>
            <p>
              <strong>"AI-Processed Data"</strong> means any output generated by artificial
              intelligence or machine learning tools used within the Services to extract, summarize,
              classify, score, or otherwise analyze permit documents or other content you submit,
              including any associated confidence scores.
            </p>
            <p>
              <strong>"Sensitive Personal Information"</strong> means Personal Data that is treated
              as sensitive under applicable law, including precise geolocation data. Our collection
              and use of Sensitive Personal Information is described in Section 3.3 and Section 9
              below.
            </p>
            <p>
              <strong>"Team Data"</strong> means Route Data, Personal Data, and other information
              associated with a Team Member's use of the Services that is visible to a Team Owner
              or Team Admin, as described in Section 6.6.
            </p>
          </div>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">3. Information We Collect</h3>

          <h4 className="mt-4 font-semibold text-gray-700">3.1 Account and Contact Information</h4>
          <p className="mt-3">
            When you create an account, we collect your name, email address, company name, and other
            contact details you provide. We also collect billing information as needed to process
            payments.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">3.2 Route Data</h4>
          <p className="mt-3">
            We collect Route Data you input or generate through the Services, including origin and
            destination addresses, load dimensions, weight specifications, waypoints, and
            permit-related information.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">3.3 Location Data</h4>
          <p className="mt-3">
            If you or your drivers use location-enabled features of the Services, we collect precise
            geolocation data from the device. This constitutes Sensitive Personal Information under
            applicable law. Location data collection occurs only when the application is in use or,
            where permitted by the user, in the background. You may disable location services
            through your device settings, but doing so may limit the functionality of the Services.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">3.4 Permit Documents and AI-Processed Data</h4>
          <p className="mt-3">
            You may submit permit documents and similar files to the Services. Where AI features are
            enabled, we process these documents using artificial intelligence or machine learning
            tools to generate AI-Processed Data, including extracted data fields and associated
            confidence scores. AI-Processed Data is returned to you as a decision-support output and
            is stored in connection with your account.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">3.5 Usage Data and Log Data</h4>
          <p className="mt-3">
            We automatically collect Usage Data when you access or use the Services, including your
            IP address, browser type, device identifiers, pages or features accessed, session
            duration, crash reports, and similar technical information.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">3.6 SMS/Text Communications Data</h4>
          <p className="mt-3">
            We collect mobile telephone numbers you submit to the Services in connection with
            account verification, one-time passcodes, and Team invitation features. We use a
            third-party SMS/text messaging service provider to send SMS/Text Communications to
            those numbers. We do not use the content of SMS/Text Communications for marketing
            purposes, and we do not share SMS opt-in data or consent with third parties for their
            own marketing purposes.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">3.7 Communications You Send Us</h4>
          <p className="mt-3">
            We collect information you provide when you contact our support team, respond to surveys,
            or otherwise communicate with us.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">3.8 Third-Party Data</h4>
          <p className="mt-3">
            We incorporate Third-Party Data — such as state DOT permit databases, bridge rating
            records, FHWA restriction data, and mapping information — into the Services. This data
            is processed to generate route plans and other outputs.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">4. How We Use Your Information</h3>

          <h4 className="mt-4 font-semibold text-gray-700">4.1 To Provide and Operate the Services</h4>
          <p className="mt-3">
            We use the information we collect to create and manage your account, process Route Data
            to generate route plans and related outputs, send SMS/Text Communications (including
            one-time passcodes, account verification messages, and Team invitation notices), process
            payments, and provide customer support.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">
            4.2 To Improve and Develop the Services
          </h4>
          <p className="mt-3">
            We use Usage Data, Derived Data, and aggregated or anonymized Route Data to analyze
            usage patterns, improve routing algorithms and AI models, conduct research, develop new
            features, and test and debug the Services. We do not use your identifiable Route Data
            or Personal Data to train AI models that are shared outside your account, except in
            aggregated or anonymized form that cannot reasonably identify you.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">4.3 To Communicate With You</h4>
          <p className="mt-3">
            We may use your contact information to send you service-related notices, security
            updates, billing communications, and (where you have opted in) product updates or
            promotional materials. You may opt out of marketing communications at any time by using
            the unsubscribe link in our emails or contacting us as described in Section 12.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">5. Third-Party Data Disclaimer</h3>
          <p className="mt-3">
            Third-Party Data incorporated into the Services — including bridge ratings, road
            restrictions, permit databases, and mapping information — is provided by external
            sources and is not independently verified by RightRoute. Third-Party Data may be
            incomplete, outdated, or inaccurate, and does not constitute a legal opinion,
            engineering assessment, or guarantee of route safety or regulatory compliance. You
            remain solely responsible for independently verifying all route outputs before
            commencing any move.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">6. How We Share Your Information</h3>

          <h4 className="mt-4 font-semibold text-gray-700">6.1 Service Providers</h4>
          <p className="mt-3">
            We share your information with third-party service providers who perform services on our
            behalf, including cloud hosting, payment processing, SMS/text messaging delivery,
            analytics, and customer support. These providers are contractually required to use your
            information only to perform services for us and to protect it in a manner consistent
            with this Privacy Policy.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">6.2 Third-Party Data Providers</h4>
          <p className="mt-3">
            To provide route planning and related features, we may submit limited Route Data
            (such as origin, destination, and load specifications) to third-party data providers
            (such as mapping APIs) as necessary to retrieve Third-Party Data. These providers are
            governed by their own privacy policies.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">6.3 Legal Requirements</h4>
          <p className="mt-3">
            We may disclose your information if required to do so by law, court order, or government
            request, or if we believe disclosure is necessary to protect the rights, property, or
            safety of RightRoute, our users, or the public.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">6.4 Business Transfers</h4>
          <p className="mt-3">
            In the event of a merger, acquisition, reorganization, or sale of all or substantially
            all of our assets, your information may be transferred to the acquiring entity. We will
            notify you of any such transfer that materially changes how your information is used.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">6.5 With Your Consent</h4>
          <p className="mt-3">
            We may share your information with third parties when you have provided your consent to
            do so.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">6.6 Team Features</h4>
          <p className="mt-3">
            If you use the Services as part of a Team, Team Data — including your Route Data,
            Personal Data, and activity within the Services — may be visible to the Team Owner and
            Team Admins of your Team. Team Owners and Admins may be able to view, manage, export,
            or delete Team Data in accordance with their account permissions. If you are a Team
            Owner or Admin, you are responsible for ensuring that your use of Team Data complies
            with applicable law and the privacy rights of your Team Members.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">7. Security</h3>
          <p className="mt-3">
            We implement technical and organizational measures designed to protect your information
            against unauthorized access, loss, or disclosure. These measures include encryption of
            data in transit and at rest, access controls, and regular security assessments.
            However, no security measure is perfect, and we cannot guarantee that your information
            will never be accessed, disclosed, or lost.
          </p>
          <p className="mt-3">
            You are responsible for maintaining the security of your account credentials and for
            notifying us promptly of any unauthorized access to your account.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">8. Data Retention</h3>
          <p className="mt-3">
            We retain your Personal Data and Route Data for as long as your account is active or as
            needed to provide the Services, comply with our legal obligations, resolve disputes, and
            enforce our agreements. Upon termination of your account, we will retain your data in
            accordance with our standard retention schedule and applicable law, and then securely
            delete or anonymize it. You may request earlier deletion of your Personal Data in
            accordance with Section 9 below.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">9. Your Privacy Rights</h3>
          <p className="mt-3">
            Depending on your location and applicable law, you may have the following rights with
            respect to your Personal Data:
          </p>
          <ul className="mt-3 list-disc space-y-3 pl-6">
            <li>The right to access the Personal Data we hold about you.</li>
            <li>The right to correct inaccurate or incomplete Personal Data.</li>
            <li>The right to request deletion of your Personal Data.</li>
            <li>
              The right to restrict or object to the processing of your Personal Data in certain
              circumstances.
            </li>
            <li>The right to data portability in certain circumstances.</li>
            <li>
              The right to opt out of the sale or sharing of your Personal Data (we do not sell
              your Personal Data).
            </li>
            <li>
              The right to limit our use of your Sensitive Personal Information (precise
              geolocation data) to purposes necessary to provide the Services.
            </li>
          </ul>
          <p className="mt-3">
            To exercise your rights, please contact us using the details in Section 12. We will
            respond to verifiable requests within the timeframes required by applicable law. Where
            we are not able to verify your identity or where applicable law does not require us to
            honor a particular request, we will notify you.
          </p>
          <p className="mt-3">
            If you are a resident of California or another state with a comprehensive privacy law
            (including Colorado, Connecticut, Virginia, Texas, Oregon, or others enacted after the
            date of this Policy), you may have additional rights under those laws. Please contact us
            for more information or to submit a rights request.
          </p>
          <p className="mt-3">
            We will not discriminate against you for exercising your privacy rights.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">10. Children</h3>
          <p className="mt-3">
            The Services are not directed to children under the age of 13, and we do not knowingly
            collect Personal Data from children. If you believe we have inadvertently collected
            information from a child, please contact us and we will take prompt steps to delete it.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">11. Data Storage and Transfer</h3>
          <p className="mt-3">
            We store your data in cloud systems located in the United States and subject to the laws
            of the United States. If you access the Services from outside the United States, your
            information will be transferred to and processed in the United States. By using the
            Services, you consent to this transfer.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">12. How to Contact Us</h3>
          <p className="mt-3">
            If you have questions about this Privacy Policy or wish to exercise your privacy rights,
            please contact us at:
          </p>
          <p className="mt-3">
            Leavitt &amp; Davis LLC
            <br />
            210 E 600 S, #1205
            <br />
            Vernal, UT 84078
            <br />
            legal@getrightroute.app
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">13. Changes to This Privacy Policy</h3>
          <p className="mt-3">
            We may update this Privacy Policy from time to time. If we make material changes, we
            will notify you by email or through a prominent notice in the Services at least 30 days
            before the changes take effect. Your continued use of the Services after the effective
            date of the revised Privacy Policy constitutes your acceptance of the changes. If you do
            not agree to the changes, you must discontinue use of the Services.
          </p>
        </section>

        <p className="mt-6">© 2026 Leavitt &amp; Davis LLC. All rights reserved.</p>
        <p>
          <a className="text-[#c3c3c3]" href="mailto:legal@getrightroute.app">
            legal@getrightroute.app
          </a>
        </p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
