const PrivacyPolicy = () => {
  return (
    <div className="max-w-5xl text-justify text-gray-600">
      <h1 className="mb-8 text-xl font-normal text-[#999] md:text-2xl">
        Privacy Policy
      </h1>
      <div className="space-y-5 leading-relaxed">
        <div>
          <h2 className="text-xl font-semibold text-gray-700">
            Leavitt &amp; Davis LLC - RightRoute Software™ Privacy Policy
          </h2>
          <p className="mt-2 italic">Last updated: 7/11/2026</p>
        </div>

        <section>
          <h3 className="font-semibold text-gray-700">1. Introduction</h3>
          <p className="mt-3">
            This Privacy Policy applies to the RightRoute Software platform and
            related services provided by Leavitt &amp; Davis LLC
            (&quot;RightRoute&quot;, &quot;we&quot;, &quot;us&quot;, or
            &quot;our&quot;). It explains how we collect, use, share, and
            protect information when you access or use RightRoute Software as a
            carrier, trucking company, broker, dispatcher, or other authorized
            user.
          </p>
          <p className="mt-3">
            By accessing or using the Services, you agree to the collection and
            use of information as described in this Privacy Policy. If you do
            not agree, you must discontinue use of the Services.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">2. Definitions</h3>
          <p className="mt-3">
            The following defined terms apply throughout this Privacy Policy:
          </p>
          <div className="mt-3 space-y-3">
            <p>
              <strong>&quot;Route Data&quot;</strong> means origin, destination,
              waypoint, road segment, bridge, height/clearance, and weight-limit
              data, as well as permit information, load specifications, and
              other operational data entered into or generated by the Services
              in connection with planning or executing an oversized load move.
            </p>
            <p>
              <strong>&quot;Personal Data&quot;</strong> means any information
              relating to an identified or identifiable natural person processed
              through the Services, including driver name, contact information,
              and device location data.
            </p>
            <p>
              <strong>&quot;Usage Data&quot;</strong> means information about how
              you interact with the Services, including feature usage, session
              duration, device and browser characteristics, and log data.
            </p>
            <p>
              <strong>&quot;Third-Party Data&quot;</strong> means data sourced
              from state departments of transportation, mapping providers, bridge
              databases, weather services, and other external data providers
              integrated with the Services.
            </p>
            <p>
              <strong>&quot;Derived Data&quot;</strong> means analytics, models,
              benchmarks, and other outputs created by RightRoute using Route
              Data, Personal Data, Usage Data, or Third-Party Data.
            </p>
            <p>
              <strong>&quot;AI-Processed Data&quot;</strong> means any output
              generated by artificial intelligence or machine learning tools used
              within the Services to extract, summarize, classify, score, or
              otherwise analyze permit documents or other content you submit,
              including any associated confidence scores.
            </p>
            <p>
              <strong>&quot;Sensitive Personal Information&quot;</strong> means
              Personal Data that is treated as sensitive under applicable law,
              including precise geolocation data. Our collection and use of
              Sensitive Personal Information is described in Section 3.3 and
              Section 9 below.
            </p>
            <p>
              <strong>&quot;Team Data&quot;</strong> means Route Data, Personal
              Data, and other information associated with a Team Member&apos;s use
              of the Services that is visible to a Team Owner or Team Admin, as
              described in Section 6.6.
            </p>
          </div>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">3. Information We Collect</h3>
          <h4 className="mt-3 font-semibold text-gray-700">
            3.1 Account and Contact Information
          </h4>
        </section>
      </div>
    </div>
  )
}

export default PrivacyPolicy
