const PrivacyPolicy = () => {
  return (
    <div className="max-w-5xl text-justify text-gray-600">
      <h1 className="mb-8 text-xl font-normal text-[#999] md:text-2xl">Privacy Policy</h1>
      <div className="space-y-5 leading-relaxed text-sm">
        <div>
          <h2 className="text-xl font-semibold text-gray-700">
            Leavitt &amp; Davis LLC - RightRoute Software™ Privacy Policy
          </h2>
          <p className="mt-2 italic">Last updated: 7/11/2026</p>
        </div>

        <section>
          <h3 className="font-semibold text-gray-700">1. Introduction</h3>
          <p className="mt-3">
            This Privacy Policy applies to the RightRoute Software platform and related services
            provided by Leavitt &amp; Davis LLC (&ldquo;RightRoute&rdquo;, &ldquo;we&rdquo;,
            &ldquo;us&rdquo;, or &ldquo;our&rdquo;). It explains how we collect, use, share, and
            protect information when you access or use RightRoute Software as a carrier, trucking
            company, broker, dispatcher, or other authorized user.
          </p>
          <p className="mt-3">
            By accessing or using the Services, you agree to the collection and use of information
            as described in this Privacy Policy. If you do not agree, you must discontinue use of
            the Services.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">2. Definitions</h3>
          <p className="mt-3">
            The following defined terms apply throughout this Privacy Policy:
          </p>
          <div className="mt-3 space-y-3">
            <p>
              <strong>&ldquo;Route Data&rdquo;</strong> means origin, destination, waypoint, road
              segment, bridge, height/clearance, and weight-limit data, as well as permit
              information, load specifications, and other operational data entered into or
              generated by the Services in connection with planning or executing an oversized load
              move.
            </p>
            <p>
              <strong>&ldquo;Personal Data&rdquo;</strong> means any information relating to an
              identified or identifiable natural person processed through the Services, including
              driver name, contact information, and device location data.
            </p>
            <p>
              <strong>&ldquo;Usage Data&rdquo;</strong> means information about how you interact
              with the Services, including feature usage, session duration, device and browser
              characteristics, and log data.
            </p>
            <p>
              <strong>&ldquo;Third-Party Data&rdquo;</strong> means data sourced from state
              departments of transportation, mapping providers, bridge databases, weather services,
              and other external data providers integrated with the Services.
            </p>
            <p>
              <strong>&ldquo;Derived Data&rdquo;</strong> means analytics, models, benchmarks, and
              other outputs created by RightRoute using Route Data, Personal Data, Usage Data, or
              Third-Party Data.
            </p>
            <p>
              <strong>&ldquo;AI-Processed Data&rdquo;</strong> means any output generated by
              artificial intelligence or machine learning tools used within the Services to extract,
              summarize, classify, score, or otherwise analyze permit documents or other content you
              submit, including any associated confidence scores.
            </p>
            <p>
              <strong>&ldquo;Sensitive Personal Information&rdquo;</strong> means Personal Data that
              is treated as sensitive under applicable law, including precise geolocation data. Our
              collection and use of Sensitive Personal Information is described in Section 3.3 and
              Section 9 below.
            </p>
            <p>
              <strong>&ldquo;Team Data&rdquo;</strong> means Route Data, Personal Data, and other
              information associated with a Team Member&rsquo;s use of the Services that is visible
              to a Team Owner or Team Admin, as described in Section 6.6.
            </p>
          </div>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">3. Information We Collect</h3>

          <h4 className="mt-4 font-semibold text-gray-700">
            3.1 Account and Contact Information
          </h4>
          <p className="mt-3">
            When you create or manage an account, we collect your name, contact details, company or
            organization information, login credentials, and user role. This information is used to
            establish and maintain your account and to communicate with you about the Services.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">
            3.2 Route Data and Load Information
          </h4>
          <p className="mt-3">
            The Services are designed to process Route Data you submit, including origin and
            destination information, load dimensions and weight specifications, permit data,
            preferred corridors, hazard or restriction overrides, and related operational data.
            This data is the core input for the Services&rsquo; routing and planning functionality.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">3.3 Location Data</h4>
          <p className="mt-3">
            If you enable location-based features, the Services may collect and process precise or
            approximate GPS location data associated with devices, vehicles, or loads. Precise
            geolocation data is treated as Sensitive Personal Information under applicable law.
            Location data may be used to provide real-time routing updates, track move progress, and
            improve routing accuracy. We collect GPS coordinates, speed, and heading through the
            Services&rsquo; route-tracking functionality on a continuous basis while location-based
            features are enabled. You may be able to manage location data collection through device
            or account settings, subject to applicable law. See Section 9 below for information on
            your right to limit the use of Sensitive Personal Information.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">3.4 Third-Party Data</h4>
          <p className="mt-3">
            The Services integrate Third-Party Data, including publicly available and licensed data
            from state departments of transportation, federal highway systems, bridge databases,
            GIS mapping providers, and weather services. RightRoute does not warrant the accuracy,
            completeness, or currency of Third-Party Data. See Section 7 (Third-Party Data
            Disclaimer) below.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">3.5 Usage Data</h4>
          <p className="mt-3">
            We automatically collect Usage Data when you access the Services, including log files,
            IP addresses, browser type, device identifiers, session length, and feature interaction
            data. We use cookies, SDKs, and similar technologies to collect Usage Data. You may
            manage certain cookie preferences through your browser settings or any in-product consent
            tools we make available.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">3.6 Support and Communications</h4>
          <p className="mt-3">
            When you contact our support team, we collect the content of your communications and
            metadata about the interaction (timestamps, issue category, resolution steps) for
            service quality and audit purposes.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">
            3.7 AI Processing of Uploaded Documents
          </h4>
          <p className="mt-3">
            When you upload permit files or other documents to the Services, we use artificial
            intelligence and machine learning tools &mdash; including third-party AI service
            providers &mdash; to extract text, classify content, and generate AI-Processed Data,
            such as extracted permit terms and associated confidence scores. This processing
            supports the permit-checklist and decision-support features described in the Terms of
            Service. AI-Processed Data is generated automatically and has not been independently
            verified by RightRoute; you remain responsible for reviewing the underlying document, as
            described in the Decision-Support Disclaimer in our Terms of Service.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">3.8 SMS/Text Communications</h4>
          <p className="mt-3">
            If you or your Team members provide a mobile telephone number to the Services &mdash;
            for example, to receive a one-time passcode or a Team invitation &mdash; we collect that
            phone number and use it, together with a third-party SMS/text messaging service
            provider, to deliver the applicable text message. We also retain a record of consent and
            opt-out status associated with that number. See the Terms of Service for the consent
            representations that apply to submitting a phone number to the Services, and Section 6.1
            below for information about our SMS/text messaging service provider.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">4. How We Use Your Information</h3>

          <h4 className="mt-4 font-semibold text-gray-700">4.1 Personal Data</h4>
          <p className="mt-3">We use Personal Data to:</p>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>Provide, operate, and maintain the Services;</li>
            <li>Authenticate your identity and manage account security;</li>
            <li>
              Communicate with you about the Services, including updates, security notices, and
              support responses;
            </li>
            <li>
              Send marketing communications about our products and services, where permitted by law
              and subject to your opt-out rights;
            </li>
            <li>
              Comply with legal and regulatory obligations and respond to lawful government requests;
              and
            </li>
            <li>
              Protect our legal rights, enforce this Privacy Policy and our Terms of Service, and
              prevent fraud or abuse.
            </li>
          </ul>

          <h4 className="mt-4 font-semibold text-gray-700">4.2 Route Data and Location Data</h4>
          <p className="mt-3">We use Route Data and Location Data to:</p>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>
              Generate route plans, clearance analyses, permit checklists, and decision-support
              outputs for your use;
            </li>
            <li>
              Improve the accuracy and reliability of the Services, including refining routing
              algorithms and updating restriction databases;
            </li>
            <li>
              Train, validate, and operate analytics and machine learning models that support
              routing recommendations and decision-support tools; and
            </li>
            <li>
              Create aggregated or anonymized data sets that do not identify you, your
              organization, or any individual, for benchmarking, research, and product improvement
              purposes.
            </li>
          </ul>
          <p className="mt-3">
            Extract and analyze permit document content using AI/machine learning tools, as
            described in Section 3.7, to generate AI-Processed Data and support permit-checklist
            features.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">4.3 Usage Data</h4>
          <p className="mt-3">
            We use Usage Data to monitor platform performance, diagnose technical issues, analyze
            feature utilization, and improve the user experience.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">5. Third-Party Data Disclaimer</h3>
          <p className="mt-3 uppercase font-medium">
            THE SERVICES INCORPORATE THIRD-PARTY DATA SOURCED FROM STATE DEPARTMENTS OF
            TRANSPORTATION, FEDERAL HIGHWAY ADMINISTRATION DATABASES, BRIDGE INSPECTION RECORDS,
            MAPPING PROVIDERS, AND OTHER EXTERNAL SOURCES. RIGHTROUTE DOES NOT INDEPENDENTLY
            VERIFY, WARRANT, OR GUARANTEE THE ACCURACY, COMPLETENESS, TIMELINESS, OR FITNESS FOR ANY
            PARTICULAR PURPOSE OF THIRD-PARTY DATA. ROUTE OUTPUTS AND RECOMMENDATIONS GENERATED BY
            THE SERVICES ARE DECISION-SUPPORT TOOLS ONLY AND MUST BE INDEPENDENTLY VERIFIED AGAINST
            APPLICABLE PERMIT CONDITIONS, STATE AND FEDERAL LOAD REGULATIONS, AND CURRENT ROAD AND
            BRIDGE CONDITIONS BEFORE RELIANCE. SEE ALSO THE DECISION-SUPPORT DISCLAIMER IN THE TERMS
            OF SERVICE.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">6. How We Share Your Information</h3>

          <h4 className="mt-4 font-semibold text-gray-700">6.1 Service Providers</h4>
          <p className="mt-3">
            We share Personal Data with third-party service providers who assist us in operating the
            Services, including cloud hosting providers, analytics vendors, and customer support
            platforms, as well as our AI/machine learning service provider (for permit-document
            processing, as described in Section 3.7) and our SMS/text messaging service provider
            (for OTP and Team invitation delivery, as described in Section 3.8). These providers
            act as processors under written agreements that limit their use of Personal Data to
            providing services to us.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">6.2 Third-Party Integrations</h4>
          <p className="mt-3">
            If you enable integrations with third-party permitting systems, mapping platforms, or
            other services, Route Data and related information may be transmitted to those third
            parties as necessary to provide the integrated functionality. Your use of third-party
            integrations is subject to those parties&rsquo; own terms and privacy policies.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">
            6.3 Aggregated and Anonymized Data
          </h4>
          <p className="mt-3">
            We may share Derived Data and aggregated or anonymized data that does not identify you,
            your organization, or any individual with third parties for research, benchmarking, and
            industry analysis purposes.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">
            6.4 Legal and Compliance Disclosures
          </h4>
          <p className="mt-3">
            We may disclose your information to government authorities, regulators, or law
            enforcement where required by law, valid legal process, or where we reasonably believe
            disclosure is necessary to protect the rights, property, or safety of RightRoute, our
            users, or the public.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">6.5 Business Transfers</h4>
          <p className="mt-3">
            In the event of a merger, acquisition, sale of assets, or similar transaction, your
            information may be transferred to the acquiring entity. We will provide notice of such a
            transfer and any material changes to this Privacy Policy as required by applicable law.
          </p>

          <h4 className="mt-4 font-semibold text-gray-700">
            6.6 Team and Multi-User Accounts
          </h4>
          <p className="mt-3">
            If you create or participate in a Team within the Services, a Team Owner or Team Admin
            may be able to view, manage, and export Team Data associated with Team Members under that
            Team. Team Members are notified within the Services of this visibility when joining a
            Team. Removal of a Team Member from a Team does not automatically delete that
            individual&rsquo;s Personal Data; retention and deletion following removal are governed
            by Section 8 (Data Retention) below.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">7. Security</h3>
          <p className="mt-3">
            We implement technical and organizational measures designed to protect your information
            against unauthorized access, loss, misuse, and alteration, including encryption in
            transit and at rest, role-based access controls, activity logging and monitoring,
            regular backups, and documented incident-response procedures. No system is completely
            secure, and we cannot guarantee that unauthorized access, hacking, data loss, or other
            breaches will never occur. We will notify affected users and applicable regulators of
            security incidents as required by applicable law, including N.D.C.C. &sect; 51-30 (North
            Dakota breach notification) and other applicable state breach notification statutes.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">8. Data Retention</h3>
          <p className="mt-3">
            We retain Personal Data and Route Data for as long as necessary to provide the Services
            and fulfill the purposes described in this Privacy Policy, unless a longer retention
            period is required or permitted by law. Upon termination of your account or written
            request, we will delete or anonymize your data in accordance with our Terms of Service
            and applicable law, subject to legal retention obligations and our legitimate
            interests in dispute resolution and fraud prevention.
          </p>
          <p className="mt-3">
            The table below sets out our retention period for each category of data we collect. Some
            categories are anonymized rather than deleted at the end of the stated period, as noted,
            to satisfy financial recordkeeping or security-audit obligations that survive account
            closure.
          </p>

          <div className="mt-4 overflow-x-auto">
            <table className="w-full border-collapse border border-gray-400 text-left text-sm text-gray-700">
              <thead className="bg-gray-50">
                <tr>
                  <th className="border border-gray-400 px-3 py-2 font-bold text-gray-900">
                    Data Category
                  </th>
                  <th className="border border-gray-400 px-3 py-2 font-bold text-gray-900">
                    Retention Period
                  </th>
                  <th className="border border-gray-400 px-3 py-2 font-bold text-gray-900">
                    Rationale
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Account / User profile
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Life of account + 3 years post-deletion
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    CCPA right-to-delete compliance; fraud prevention
                  </td>
                </tr>
                <tr>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    OTP verification records
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    90 days after verification or expiry
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Security audit trail
                  </td>
                </tr>
                <tr>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Team &amp; membership data
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Life of Team + 1 year
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Contractual / operational need
                  </td>
                </tr>
                <tr>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Payment method tokens
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Until you remove the method or your account is deleted
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    User control; subject to processor retention
                  </td>
                </tr>
                <tr>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Payment transactions
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    7 years (anonymized, not deleted, after account closure)
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    U.S. tax / financial recordkeeping requirements
                  </td>
                </tr>
                <tr>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Subscription records
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    7 years post-expiration
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Financial compliance
                  </td>
                </tr>
                <tr>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Route &amp; waypoint data
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Life of account + 2 years
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Operational need; legal hold
                  </td>
                </tr>
                <tr>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    GPS route tracking
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    1 year, rolling
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Storage minimization; limits retention of precise location data
                  </td>
                </tr>
                <tr>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Permit files
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Life of the associated route + 2 years
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Regulatory / legal hold
                  </td>
                </tr>
                <tr>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Notifications
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    6 months after read; 1 year if unread
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Operational need
                  </td>
                </tr>
                <tr>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Activity / audit logs
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    3 years (anonymized, not deleted, after account closure)
                  </td>
                  <td className="border border-gray-400 px-3 py-2 align-top text-gray-800">
                    Security, compliance, fraud investigation
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">9. Your Privacy Rights</h3>
          <p className="mt-3">
            Depending on your location and applicable law, you may have the following rights
            regarding your Personal Data:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>
              <strong>Access:</strong> to request a copy of the Personal Data we hold about you;
            </li>
            <li>
              <strong>Correction:</strong> to request correction of inaccurate or incomplete
              Personal Data;
            </li>
            <li>
              <strong>Deletion:</strong> to request deletion of your Personal Data, subject to legal
              retention obligations (as described in Section 8, certain categories &mdash; such as
              payment transaction records and activity logs &mdash; are anonymized rather than
              deleted in order to satisfy those obligations);
            </li>
            <li>
              <strong>Restriction and Objection:</strong> to request that we limit certain processing
              or object to processing based on our legitimate interests;
            </li>
            <li>
              <strong>Portability:</strong> to receive certain Personal Data in a structured,
              machine-readable format;
            </li>
            <li>
              <strong>Marketing opt-out:</strong> to opt out of marketing communications at any
              time; and
            </li>
            <li>
              <strong>U.S. State Rights (for eligible residents):</strong> users in California and
              other states with applicable privacy statutes may have additional rights, including the
              right to opt out of the &ldquo;sale&rdquo; or &ldquo;sharing&rdquo; of Personal Data and
              to limit the use of sensitive Personal Data.
            </li>
          </ul>

          <h4 className="mt-4 font-semibold text-gray-700">
            Limiting the Use of Sensitive Personal Information
          </h4>
          <p className="mt-3">
            Where required by applicable law, you have the right to limit our use of Sensitive
            Personal Information &mdash; including precise geolocation data &mdash; to purposes
            necessary to provide the Services. You may exercise this right using the in-product
            control described as &ldquo;Limit the Use of My Sensitive Personal Information&rdquo; in
            your account settings, or by contacting us using the details in Section 12 below.
            Limiting the use of precise geolocation data may affect the availability of real-time
            routing, move-progress tracking, and related features.
          </p>
          <p className="mt-3">
            To exercise these rights, contact us using the details in Section 12 below or through
            any account-based self-service tools we make available. We will respond within the time
            required by applicable law after verifying your identity.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">10. Children</h3>
          <p className="mt-3">
            The Services are not directed to individuals under 18 years of age. We do not knowingly
            collect Personal Data from children. If you believe we have inadvertently collected
            information from a child, please contact us and we will take prompt steps to delete it.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">11. Data Storage and Transfer</h3>
          <p className="mt-3">
            We store your data in cloud systems located in the United States and subject to the laws
            of the United States. If you access the Services from outside the United States, your
            information will be transferred to and processed in the United States. By using the
            Services, you consent to this transfer.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">12. How to Contact Us</h3>
          <p className="mt-3">
            If you have questions about this Privacy Policy or wish to exercise your privacy rights,
            please contact us at:
          </p>
          <p className="mt-3">
            Leavitt &amp; Davis LLC
            <br />
            210 E 600 S, #1205
            <br />
            Vernal, UT 84078
            <br />
            <a
              className="text-[#c3c3c3] hover:underline"
              href="mailto:legal@getrightroute.app"
            >
              legal@getrightroute.app
            </a>
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">13. Changes to This Privacy Policy</h3>
          <p className="mt-3">
            We may update this Privacy Policy from time to time. If we make material changes, we
            will notify you by email or through a prominent notice in the Services at least 30 days
            before the changes take effect. Your continued use of the Services after the effective
            date of the revised Privacy Policy constitutes your acceptance of the changes. If you do
            not agree to the changes, you must discontinue use of the Services.
          </p>
        </section>

        <p className="mt-6">&copy; 2026 Leavitt &amp; Davis LLC. All rights reserved.</p>
        <p>
          <a className="text-[#c3c3c3]" href="mailto:legal@getrightroute.app">
            legal@getrightroute.app
          </a>
        </p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
