const TermsOfUse = () => {
  return (
    <div className="max-w-5xl text-justify text-gray-600">
      <h1 className="text-2xl font-medium mb-4 text-black/40">
        Terms of Service
      </h1>
      <div className="space-y-5 leading-relaxed">
        <div>
          <h2 className="text-xl font-semibold text-gray-700">
            Leavitt &amp; Davis LLC - RightRoute™ Terms of Service
          </h2>
          <p className="mt-2 italic">Last updated: 7/11/2026</p>
        </div>

        <section>
          <h3 className="font-semibold text-gray-700">Important Notice</h3>
          <p className="mt-3 font-semibold uppercase">
            PLEASE READ THESE TERMS OF SERVICE CAREFULLY BEFORE ACCESSING OR
            USING THE SERVICES. THIS AGREEMENT CONTAINS IMPORTANT LIMITATIONS
            OF LIABILITY, INDEMNITY OBLIGATIONS, A BINDING ARBITRATION CLAUSE,
            AND A DECISION-SUPPORT DISCLAIMER THAT AFFECT YOUR LEGAL RIGHTS.
            BY ACCESSING OR USING THE SERVICES, YOU AGREE TO BE BOUND BY THIS
            AGREEMENT. IF YOU DO NOT AGREE, DO NOT ACCESS OR USE THE SERVICES.
          </p>
        </section>

        <section>
          <h3 className="font-semibold text-gray-700">1. Definitions</h3>
          <p className="mt-3">The following capitalized terms have the meanings set forth below:</p>
          <ul className="mt-3 list-disc space-y-3 pl-6">
            <li>
              <strong>“Agreement”</strong> means these Terms of Service,
              together with any applicable order forms, schedules, or addenda,
              and the RightRoute Privacy Policy, all of which are incorporated
              herein by reference.
            </li>
            <li>
              <strong>“Services”</strong> means the software-as-a-service
              platform and related cloud services, APIs, integrations, and
              customer support made available by LEAVITT &amp; DAVIS LLC at
              https://getrightroute.app, as further described in applicable
              documentation.
            </li>
            <li>
              <strong>“Route Data”</strong> means origin, destination,
              waypoint, road segment, bridge clearance and rating, weight and
              height restriction, permit, load specification, and related
              operational data entered into, processed by, or generated by the
              Services.
            </li>
            <li>
              <strong>“Personal Data”</strong> means any information relating
              to an identified or identifiable natural person processed through
              the Services.
            </li>
            <li>
              <strong>“Third-Party Data”</strong> means data sourced from state
              departments of transportation, federal highway databases, bridge
              inspection records, GIS mapping providers, weather services, and
              other external sources integrated with the Services.
            </li>
            <li>
              <strong>“Derived Data”</strong> means analytics, models,
              benchmarks, and other outputs generated by LEAVITT &amp; DAVIS LLC
              from Route Data, Personal Data, or Third-Party Data.
            </li>
            <li>
              <strong>“AI-Processed Data”</strong> means any output generated
              by artificial intelligence or machine learning tools used within
              the Services to extract, summarize, classify, score, or otherwise
              analyze permit documents, Route Data, or other content submitted
              by a User, including any associated confidence scores.
            </li>
            <li>
              <strong>“SMS/Text Communications”</strong> means any text, SMS,
              or MMS message sent by or on behalf of RightRoute, including
              through a third-party SMS/text messaging service provider, to a
              mobile telephone number in connection with the Services,
              including one-time passcodes, account verification codes, and Team
              invitation notices.
            </li>
            <li>
              <strong>“User”</strong> means any carrier, trucking company,
              broker, dispatcher, or other person or entity who accesses or uses
              the Services under this Agreement, including any person granted
              access by you.
            </li>
          </ul>
        </section>
      </div>
    </div>
  );
};

export default TermsOfUse;
